### ISSUE TITLE
Segfault with outgoing energy distribution having a single incident energy

### ISSUE THREAD

**Issue by paulromano** [openmc-dev/openmc#1098]
A user reported a segfault to me trying to use a randomly generated TENDL file. The issue was that in their file, the delayed neutron energy distributions only had a single incident energy point, which eventually caused an out-of-bounds error in `ContinuousTabular::sample`. I'm not 100% sure the data can be considered correct in this case, but nevertheless OpenMC should probably fail a little more gracefully in such a situation.

**Comment by Shimwell** [comment]
I am having similar difficulties with TENDL 2015.

After writing a download script for TENDL-2017 ([link to tendl-2017 script](https://github.com/Shimwell/openmc/blob/download_tendl_data/scripts/openmc-get-tendl-2017-data)) and getting an NJOY with Boron 10 ([link to issue](https://groups.google.com/forum/#!searchin/openmc-users/tendl%7Csort:date/openmc-users/EhmXaYBfQPk/J4WbgJ7hAgAJ)) I started trying to use TENDL-2015

I have written a openmc-get-tendl-2015-data script ([link to tendl-2015 script](https://github.com/Shimwell/openmc/blob/download_tendl_data/scripts/openmc-get-tendl-2015-data)) which downloads the ace files and converts them to h5 (based on the nndc and JEFF scripts). [](url)

When I try to run openmc with the TENDL 2015 h5 files I get this error and a segfault, perhaps this is the same segfault as previously reported. When I plot the cross section (MT101) it appears fine.

```
Initializing source particles...
 ===============>     FIXED SOURCE TRANSPORT SIMULATION     <===============

 Simulating batch 1
 ERROR:  Did not sample any reaction for nuclide Si28
ERROR STOP 
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Traceback (most recent call last):
  File "simulate_sphere_model.py", line 209, in <module>
    temperature_in_C=500
  File "simulate_sphere_model.py", line 156, in make_materials_geometry_tallies
    model.run()
  File "/home/jshim/.local/lib/python3.6/site-packages/openmc-0.10.0-py3.6-linux-x86_64.egg/openmc/model/model.py", line 204, in run
    openmc.run(**kwargs)
  File "/home/jshim/.local/lib/python3.6/site-packages/openmc-0.10.0-py3.6-linux-x86_64.egg/openmc/executor.py", line 212, in run
    _run(args, output, cwd)
  File "/home/jshim/.local/lib/python3.6/site-packages/openmc-0.10.0-py3.6-linux-x86_64.egg/openmc/executor.py", line 30, in _run
    ''.join(lines))
subprocess.CalledProcessError: Command 'openmc' died with <Signals.SIGABRT: 6>.
```

**Comment by paulromano** [comment]
Here's my own HDF5 library for TENDL 2015 that I used to test:
https://anl.box.com/s/tb00nfpju77yptl5cia01ljvvg2syekg
