### ISSUE TITLE
Cross section library does not exist

### ISSUE THREAD

**Issue by EarnestTrout** [openmc-dev/openmc#1917]
Hello, I am currently running into issues with my cross section library. When attempting to run a code, I get a warning that all these cross sections don't exist at that directory but they do really exist exactly at that directory. I included the code and also a screenshot showing the directory of said "missing" data.
```
Reading settings XML file...
 Reading cross sections XML file...
 WARNING: Cross section library $Home/OpenMC/Lib/jeff33_hdf5/H1.h5 does not
          exist.
 WARNING: Cross section library $Home/OpenMC/Lib/jeff33_hdf5/photon/Fm.h5 does
          not exist.
 Reading materials XML file...
 Reading geometry XML file...
 ERROR: Could not find material 13 specified on cell 1
Traceback (most recent call last):
  File "/home/ernest/OpenMC/Code/GEH_V1_Tallies.py", line 251, in <module>
    openmc.run()
  File "/home/ernest/miniconda3/envs/openmc-env/lib/python3.9/site-packages/openmc/executor.py", line 227, in run
    _run(args, output, cwd)
  File "/home/ernest/miniconda3/envs/openmc-env/lib/python3.9/site-packages/openmc/executor.py", line 38, in _run
    raise RuntimeError(error_msg)
RuntimeError: Could not find material 13 specified on cell 1
(openmc-env) ernest@ernest-TUF-GAMING-FX504GD-FX80GD:~/OpenMC/Co
```
![Screenshot from 2021-11-27 18-10-08](https://user-images.githubusercontent.com/94420313/143722904-aa6639ec-84be-4c2a-9837-fb6c7389d5ef.png)

**Comment by makeclean** [comment]
In your cross_sections.xml file you haven't put the $HOME variable in that file have you? If you have, this is shell variable and only processable via the shell, the OpenMC program can't do anything with it.

**Comment by EarnestTrout** [comment]
@makeclean Sorry I'm new to using linux, I have the cross sections defined with `<directory>$Home/OpenMC/Lib/jeff33_hdf5</directory>`. Would the proper way to define it be `<directory>OpenMC/Lib/jeff33_hdf5</directory>`?

**Comment by shimwell** [comment]
Perhaps replace `$HOME` with `/home/ernest`

**Comment by makeclean** [comment]
Did @shimwell's suggestion work for you @EarnestTrout ?

**Comment by EarnestTrout** [comment]
@shimwell @makeclean sorry this fix did not work, the same warning is showing up.

**Comment by shimwell** [comment]
Does this screen shot of my cross_sections.xml and folder contents help, I notice that I am using relative paths. Relative to the location of the cross_section.xml file.

![Screenshot from 2021-11-29 07-35-15](https://user-images.githubusercontent.com/8583900/143826504-10e958d6-149f-4b19-8a79-890fbcfab8b2.png)

**Comment by shimwell** [comment]
If changing to relative paths does not help then I have one more option. You could take a look at this python package I wrote that downloads data on the fly and sets makes the cross_section.xml file (with correct paths) automatically.

https://github.com/openmc-data-storage/openmc_data_downloader

**Comment by EarnestTrout** [comment]
@shimwell I purged HDF5 and removed OpenMC, and reinstalled them both. And am now getting a HDF5 error after the warning about the cross sections not existing. 
```
 Reading materials XML file...
 Reading geometry XML file...
 Reading Na23 from /home/OpenMC/CrossSec/jeff33_hdf5/Na23.h5
HDF5-DIAG: Error detected in HDF5 (1.12.1) thread 1:
  #000: H5F.c line 620 in H5Fopen(): unable to open file
    major: File accessibility
    minor: Unable to open file
  #001: H5VLcallback.c line 3501 in H5VL_file_open(): failed to iterate over available VOL connector plugins
    major: Virtual Object Layer
    minor: Iteration failed
  #002: H5PLpath.c line 578 in H5PL__path_table_iterate(): can't iterate over plugins in plugin path '(null)'
    major: Plugin for dynamically loaded library
    minor: Iteration failed
  #003: H5PLpath.c line 620 in H5PL__path_table_iterate_process_path(): can't open directory: /home/ernest/miniconda3/envs/openmc-env/lib/hdf5/plugin
    major: Plugin for dynamically loaded library
    minor: Can't open directory or file
  #004: H5VLcallback.c line 3351 in H5VL__file_open(): open failed
    major: Virtual Object Layer
    minor: Can't open object
  #005: H5VLnative_file.c line 97 in H5VL__native_file_open(): unable to open file
    major: File accessibility
    minor: Unable to open file
  #006: H5Fint.c line 1834 in H5F_open(): unable to open file: name = '/home/OpenMC/CrossSec/jeff33_hdf5/Na23.h5', tent_flags = 0
    major: File accessibility
    minor: Unable to open file
  #007: H5FD.c line 723 in H5FD_open(): open failed
    major: Virtual File Layer
    minor: Unable to initialize object
  #008: H5FDsec2.c line 352 in H5FD__sec2_open(): unable to open file: name = '/home/OpenMC/CrossSec/jeff33_hdf5/Na23.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0
    major: File accessibility
    minor: Unable to open file
 ERROR: Failed to open HDF5 file with mode 'r':
        /home/OpenMC/CrossSec/jeff33_hdf5/Na23.h5
Traceback (most recent call last):
  File "/home/ernest/OpenMC/Code/GEH_V1.py", line 229, in <module>
    openmc.run()
  File "/home/ernest/miniconda3/envs/openmc-env/lib/python3.9/site-packages/openmc/executor.py", line 227, in run
    _run(args, output, cwd)
  File "/home/ernest/miniconda3/envs/openmc-env/lib/python3.9/site-packages/openmc/executor.py", line 38, in _run
    raise RuntimeError(error_msg)
RuntimeError: Failed to open HDF5 file with mode 'r': /home/OpenMC/CrossSec/jeff33_hdf5/Na23.h5
```

**Comment by makeclean** [comment]
@EarnestTrout I think your path is still wrong, shouldn't `/home/OpenMC/CrossSec/jeff33_hdf5/Na23.h5` be `/home/ernest/OpenMC/CrossSec/jeff33_hdf5/Na23.h5`
