### ISSUE TITLE
examples/pincell_depletion is broken

### ISSUE THREAD

**Issue by gridley** [openmc-dev/openmc#1927]
It appears some changes to the `openmc.model.Model` (formerly `openmc.Model`) have broken this example. We erroneously attempt to use `openmc.Model` and also the interface to `get_all_materials` also appears to have changed, causing the `run_depletion.py` script to fail.

EDIT: perhaps this affects all depletion calculatoins at present. It seems that the depletion operator is using the wrong `get_all_materials` method?

```
Traceback (most recent call last):
  File "/home/gavin/Code/openmc/examples/pincell_depletion/run_depletion.py", line 91, in <module>
    op = openmc.deplete.Operator(model, chain_file)
  File "/home/gavin/.local/lib/python3.9/site-packages/openmc-0.12.1.dev0-py3.9.egg/openmc/deplete/operator.py", line 221, in __init__
    self.burnable_mats, volume, nuclides = self._get_burnable_mats()
  File "/home/gavin/.local/lib/python3.9/site-packages/openmc-0.12.1.dev0-py3.9.egg/openmc/deplete/operator.py", line 409, in _get_burnable_mats
    for mat in self.geometry.get_all_materials().values():
AttributeError: 'Model' object has no attribute 'get_all_materials'

```

**Comment by gridley** [comment]
Oops. Just had to reinstall my python API :)
