### ISSUE TITLE
OpenMC installation fail

### ISSUE THREAD

**Issue by vprst** [openmc-dev/openmc#2057]
Hi, 

I am trying to install OpenMC on Linux via conda-forge but I have the following issues:

ERROR REPORT:
```
    Traceback (most recent call last):
      File "/home/vpr/miniconda3/lib/python3.8/site-packages/conda/exceptions.py", line 1082, in __call__
        return func(*args, **kwargs)
      File "/home/vpr/miniconda3/lib/python3.8/site-packages/conda/cli/main.py", line 87, in _main
        exit_code = do_call(args, p)
      File "/home/vpr/miniconda3/lib/python3.8/site-packages/conda/cli/conda_argparse.py", line 84, in do_call
        return getattr(module, func_name)(args, parser)
      File "/home/vpr/miniconda3/lib/python3.8/site-packages/conda/cli/main_create.py", line 41, in execute
        install(args, parser, 'create')
      File "/home/vpr/miniconda3/lib/python3.8/site-packages/conda/cli/install.py", line 260, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/home/vpr/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/home/vpr/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 195, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/home/vpr/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 300, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/home/vpr/miniconda3/lib/python3.8/site-packages/conda/common/io.py", line 88, in decorated
        return f(*args, **kwds)
      File "/home/vpr/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 463, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/home/vpr/miniconda3/lib/python3.8/site-packages/conda/core/solve.py", line 1058, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/home/vpr/miniconda3/lib/python3.8/site-packages/conda/core/index.py", line 291, in get_reduced_index
        push_record(record)
      File "/home/vpr/miniconda3/lib/python3.8/site-packages/conda/core/index.py", line 265, in push_record
        combined_depends = record.combined_depends
      File "/home/vpr/miniconda3/lib/python3.8/site-packages/conda/models/records.py", line 340, in combined_depends
        result = {ms.name: ms for ms in MatchSpec.merge(self.depends)}
      File "/home/vpr/miniconda3/lib/python3.8/site-packages/conda/models/match_spec.py", line 478, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/home/vpr/miniconda3/lib/python3.8/site-packages/conda/models/match_spec.py", line 478, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/home/vpr/miniconda3/lib/python3.8/site-packages/conda/models/match_spec.py", line 509, in _merge
        final = this_component.merge(that_component)
      File "/home/vpr/miniconda3/lib/python3.8/site-packages/conda/models/match_spec.py", line 760, in merge
        raise ValueError("Incompatible component merge:\n  - %r\n  - %r"
    ValueError: Incompatible component merge:
      - 'mpi_mpich_*'
      - 'mpi_mpich_tempest*'

$ /home/vpr/miniconda3/bin/conda create -n openmc-env openmc

active environment : base
active env location : /home/vpr/miniconda3
shell level : 1
user config file : /home/vpr/.condarc
populated config files : /home/vpr/.condarc
conda version : 4.12.0
conda-build version : not installed
python version : 3.8.13.final.0
virtual packages : __linux=5.10.16.3=0
                          __glibc=2.31=0
                          __unix=0=0
                          __archspec=1=x86_64
base environment : /home/vpr/miniconda3  (writable)
conda av data dir : /home/vpr/miniconda3/etc/conda
conda av metadata url : None
channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
package cache : /home/vpr/miniconda3/pkgs
                          /home/vpr/.conda/pkgs
envs directories : /home/vpr/miniconda3/envs
                          /home/vpr/.conda/envs
platform : linux-64
user-agent : conda/4.12.0 requests/2.27.1 CPython/3.8.13 Linux/5.10.16.3-microsoft-standard-WSL2 ubuntu/20.04.4 glibc/2.31
UID:GID : 1000:1000
netrc file : None
offline mode : False

```

I haven't found a similar issue here, let me know if this is something that you have encountered before.
Thanks in advance for your help with this.

**Comment by vprst** [comment]
Thanks for the help @shimwell, mamba worked and I sucessfully installed openmc.

**Comment by lz152** [comment]
thank god!
