### ISSUE TITLE
Testing error after buiding from source on Ubuntu 22.04: AttributeError: module 'openmc' has no attribute 'main'. Did you mean: 'chain'?

### ISSUE THREAD

**Issue by partofthething** [openmc-dev/openmc#2091]
I'm sure I'm doing something dumb here but, I'm trying to install from source on Ubuntu 22.04 (which btw has Python 3.10). It compiles fine but when I try the testing with pytest I always get failures. I tried running just the first test. I did run the download-xs script in advance and am just trying to follow the [testing instructions](https://docs.openmc.org/en/stable/devguide/tests.html) right after building. 

```
(openmc) nick@lemur:~/code/openmc/tests$ pytest  regression_tests/adj_cell_rotation/test.py 
============================================ test session starts =============================================
platform linux -- Python 3.10.4, pytest-7.1.2, pluggy-0.13.0
rootdir: /home/nick/code/openmc, configfile: pytest.ini
plugins: cov-3.0.0
collected 1 item                                                                                             

regression_tests/adj_cell_rotation/test.py F                                                           [100%]

================================================== FAILURES ==================================================
_______________________________________________ test_rotation ________________________________________________

model = <openmc.model.model.Model object at 0x7fd685a240a0>

    def test_rotation(model):
        harness = PyAPITestHarness('statepoint.10.h5', model)
>       harness.main()

/home/nick/code/openmc/tests/regression_tests/adj_cell_rotation/test.py:50: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
/home/nick/code/openmc/tests/testing_harness.py:298: in main
    self.execute_test()
/home/nick/code/openmc/tests/testing_harness.py:307: in execute_test
    self._run_openmc()
/home/nick/code/openmc/tests/testing_harness.py:72: in _run_openmc
    openmc.run(openmc_exec=config['exe'], event_based=config['event'])
/home/nick/code/openmc/openmc/executor.py:276: in run
    _run(args, output, cwd)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

args = ['openmc']
output = 'Traceback (most recent call last):\n  File "/srv/venvs/openmc/bin/openmc", line 33, in <module>\n    sys.exit(load_en...educe(getattr, attrs, module)\nAttributeError: module \'openmc\' has no attribute \'main\'. Did you mean: \'chain\'?\n'
cwd = '.'

    def _run(args, output, cwd):
        # Launch a subprocess
        p = subprocess.Popen(args, cwd=cwd, stdout=subprocess.PIPE,
                             stderr=subprocess.STDOUT, universal_newlines=True)
    
        # Capture and re-print OpenMC output in real-time
        lines = []
        while True:
            # If OpenMC is finished, break loop
            line = p.stdout.readline()
            if not line and p.poll() is not None:
                break
    
            lines.append(line)
            if output:
                # If user requested output, print to screen
                print(line, end='')
    
        # Raise an exception if return status is non-zero
        if p.returncode != 0:
            # Get error message from output and simplify whitespace
            output = ''.join(lines)
            if 'ERROR: ' in output:
                _, _, error_msg = output.partition('ERROR: ')
            elif 'what()' in output:
                _, _, error_msg = output.partition('what(): ')
            else:
                error_msg = 'OpenMC aborted unexpectedly.'
            error_msg = ' '.join(error_msg.split())
    
>           raise RuntimeError(error_msg)
E           RuntimeError: OpenMC aborted unexpectedly.

/home/nick/code/openmc/openmc/executor.py:116: RuntimeError
-------------------------------------------- Captured stdout call --------------------------------------------
Traceback (most recent call last):
  File "/srv/venvs/openmc/bin/openmc", line 33, in <module>
    sys.exit(load_entry_point('armicontrib-openmc', 'console_scripts', 'openmc')())
  File "/srv/venvs/openmc/bin/openmc", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/lib/python3.10/importlib/metadata/__init__.py", line 173, in load
    return functools.reduce(getattr, attrs, module)
AttributeError: module 'openmc' has no attribute 'main'. Did you mean: 'chain'?

```

**Comment by partofthething** [comment]
yeah that's it, sorry for the noise.
