### ISSUE TITLE
Can't link `summary.h5` file when using `Model.init_lib()` for running `MicroXS.from_model()`

### ISSUE THREAD

**Issue by yardasol** [openmc-dev/openmc#2172]
I am trying to run a validation simulation for the new transport-independent depletion feature on HPC architecture. To get all the right MPI intracommunicator, I am running `Model.init_lib()` before passing my `Model` object to `MicroXS.from_model()`. This produces the following error:

```bash
Traceback (most recent call last):
  File "/home/ooblack/projects/2023-openmc-depletion-data/problem_setup.py", line 75, in <module>
    micro_xs = MicroXS.from_model(model, materials[0], chain_file)
  File "/home/ooblack/projects/openmc/openmc/deplete/microxs.py", line 108, in from_model
    xs[rx].load_from_statepoint(sp)
  File "/home/ooblack/projects/openmc/openmc/mgxs/mgxs.py", line 994, in load_from_statepoint
    raise ValueError(msg)
ValueError: Unable to load data from a statepoint which has not been linked with a summary file
```
I believe that this error is caused by our use of a `TemporaryDirectory` in `from_model()` to avoid overwriting the user's `material.xml` and `tallies.xml` files. On initialization, the `StatePoint` object tries to link to a `summary.h5` file that is assumed to be in the same directory as the statepoint file. When using just the python API, both the statepoint file and the summary file are written to the current working directory. Howver, after calling `init_lib()`, the statepoint file is written to 
the temporary directory, but the summary file is still written to the original current working directory.

The `settings.output.path` variable provides a fix provided that the variable is set before calling `Model.init_lib()`. Unfortunately, this use-case has the user calling `Model.init_lib()` before the `from_model()` function.

This issue can be closed when a PR exists that adds machinery to `MicroXS.from_model()` that allows error-free use of a model that has the shared library initialized.

**Comment by yardasol** [comment]
closed by #2212
