### ISSUE TITLE
conda install openmc fails

### ISSUE THREAD

**Issue by tkittel** [openmc-dev/openmc#2184]
I am playing around with conda, and everything appears to be in order with my installation. For instance, a simple `conda install root` or `conda install geant4` worked without a hitch. However, `conda install openmc` fails on two different platforms (ubuntu 20.04 & CentOS8) with:

```
Collecting package metadata (current_repodata.json): failed

# >>>>>>>>>>>>>>>>>>>>>> ERROR REPORT <<<<<<<<<<<<<<<<<<<<<<

    Traceback (most recent call last):
      File "/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/lib/python3.9/site-packages/conda/exceptions.py", line 1114, in __call__
        return func(*args, **kwargs)
      File "/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/lib/python3.9/site-packages/conda/cli/main.py", line 86, in main_subshell
        exit_code = do_call(args, p)
      File "/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/lib/python3.9/site-packages/conda/cli/conda_argparse.py", line 90, in do_call
        return getattr(module, func_name)(args, parser)
      File "/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/lib/python3.9/site-packages/conda/cli/main_install.py", line 20, in execute
        install(args, parser, 'install')
      File "/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/lib/python3.9/site-packages/conda/cli/install.py", line 259, in install
        unlink_link_transaction = solver.solve_for_transaction(
      File "/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/lib/python3.9/site-packages/conda/core/solve.py", line 152, in solve_for_transaction
        unlink_precs, link_precs = self.solve_for_diff(update_modifier, deps_modifier,
      File "/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/lib/python3.9/site-packages/conda/core/solve.py", line 195, in solve_for_diff
        final_precs = self.solve_final_state(update_modifier, deps_modifier, prune, ignore_pinned,
      File "/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/lib/python3.9/site-packages/conda/core/solve.py", line 300, in solve_final_state
        ssc = self._collect_all_metadata(ssc)
      File "/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/lib/python3.9/site-packages/conda/common/io.py", line 86, in decorated
        return f(*args, **kwds)
      File "/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/lib/python3.9/site-packages/conda/core/solve.py", line 463, in _collect_all_metadata
        index, r = self._prepare(prepared_specs)
      File "/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/lib/python3.9/site-packages/conda/core/solve.py", line 1058, in _prepare
        reduced_index = get_reduced_index(self.prefix, self.channels,
      File "/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/lib/python3.9/site-packages/conda/core/index.py", line 290, in get_reduced_index
        push_record(record)
      File "/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/lib/python3.9/site-packages/conda/core/index.py", line 264, in push_record
        combined_depends = record.combined_depends
      File "/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/lib/python3.9/site-packages/conda/models/records.py", line 340, in combined_depends
        result = {ms.name: ms for ms in MatchSpec.merge(self.depends)}
      File "/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/lib/python3.9/site-packages/conda/models/match_spec.py", line 476, in merge
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/lib/python3.9/site-packages/conda/models/match_spec.py", line 476, in <lambda>
        reduce(lambda x, y: x._merge(y, union), group) if len(group) > 1 else group[0]
      File "/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/lib/python3.9/site-packages/conda/models/match_spec.py", line 507, in _merge
        final = this_component.merge(that_component)
      File "/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/lib/python3.9/site-packages/conda/models/match_spec.py", line 758, in merge
        raise ValueError("Incompatible component merge:\n  - %r\n  - %r"
    ValueError: Incompatible component merge:
      - 'mpi_mpich_*'
      - 'mpi_mpich_tempest*'

`$ /mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/bin/conda install openmc`

  environment variables:
                 CIO_TEST=<not set>
        CONDA_DEFAULT_ENV=foobar
                CONDA_EXE=/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/
                          bin/conda
             CONDA_PREFIX=/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/
                          envs/foobar
           CONDA_PREFIX_1=/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed
    CONDA_PROMPT_MODIFIER=(foobar)
         CONDA_PYTHON_EXE=/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/
                          bin/python
               CONDA_ROOT=/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed
              CONDA_SHLVL=2
           CURL_CA_BUNDLE=<not set>
                  MANPATH=::/opt/puppetlabs/puppet/share/man
               MODULEPATH=/usr/share/Modules/modulefiles:/etc/modulefiles:/usr/share/modulefiles
                     PATH=/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/
                          bin:/mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_instal
                          led/envs/foobar/bin:/mnt/groupdata/detector/workspaces/thki/miniforge/
                          miniforge_installed/condabin:/users/thki/scr/miniforge/miniforge_insta
                          lled/bin:/mnt/groupdata/detector/dgcode_installs/git_v2.22.1/bin/bin:/
                          usr/share/Modules/bin:/usr/local/bin:/usr/bin:/usr/local/sbin:/usr/sbi
                          n:/opt/puppetlabs/bin:/users/thki/bin
       REQUESTS_CA_BUNDLE=<not set>
            SSL_CERT_FILE=<not set>
               http_proxy=<set>
              https_proxy=<set>
                 no_proxy=<set>

     active environment : foobar
    active env location : /mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/envs/foobar
            shell level : 2
       user config file : /users/thki/.condarc
 populated config files : /mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/.condarc
          conda version : 4.13.0
    conda-build version : not installed
         python version : 3.9.13.final.0
       virtual packages : __linux=4.18.0=0
                          __glibc=2.28=0
                          __unix=0=0
                          __archspec=1=x86_64
       base environment : /mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed  (writable)
      conda av data dir : /mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/etc/conda
  conda av metadata url : None
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/pkgs
                          /users/thki/.conda/pkgs
       envs directories : /mnt/groupdata/detector/workspaces/thki/miniforge/miniforge_installed/envs
                          /users/thki/.conda/envs
               platform : linux-64
             user-agent : conda/4.13.0 requests/2.28.1 CPython/3.9.13 Linux/4.18.0-193.el8.x86_64 centos/8.2.2004 glibc/2.28
                UID:GID : 5068:5068
             netrc file : None
           offline mode : False


An unexpected error has occurred. Conda has prepared the above report.
```
Sorry if this is not the right project for conda/openmc related issues.

Cheers,
Thomas

**Comment by shimwell** [comment]
Hi Thomas

Thanks for raising this issue, I think this has come up before in issue #https://github.com/openmc-dev/openmc/issues/2057 which has some solutions.

Since the closing of https://github.com/openmc-dev/openmc/issues/2057  we have also updated the documentation installation section.

The [latest documentation now suggests using mamba](
https://docs.openmc.org/en/latest/quickinstall.html#), just wondering if these instructions work for you

Another option if the latest docs method doesn't work for you is to specify particular versions in the install command. I often use this command.

```bash
conda install -c conda-forge mamba
mamba install -c conda-forge -y "openmc=0.13.0=*nompi*"
```

Let us know how these three options works out for you

**Comment by tkittel** [comment]
Thanks for the quick feedback! I am not actually using OpenMC myself (yet!), but several colleagues are :-)

I can confirm that the commands above seem to work, although I guess it is not actually intended in the long run to force users to use mamba instead of Conda, and that this is just a short-term workaround for a bug? Or are there more underlying issues with Conda?

Cheers,
Thomas

**Comment by shimwell** [comment]
Thanks for confirming the commands worked :+1: , I'm going to go ahead and close this issue here as I think this bug has come up before on issue https://github.com/openmc-dev/openmc/issues/2057 and unfortunately it was concluded that it can't be fixed on the OpenMC side.

Longer term it would be ideal to support both mamba and conda installs. Or perhaps conda will use the mamba solver by default.

mamba currently has some advantages (it is much faster) and it works :smile: 

On issue https://github.com/openmc-dev/openmc/issues/2057 there was a link to the underlying issue with conda https://github.com/conda/conda/issues/11442 if you want to take a peak

Best of luck with the project and perhaps see you at the [monthly gatherings sometime](https://openmc.discourse.group/t/openmc-monthly-drop-in-session-dates-2022/1629), would be super interested to hear more about ESS

**Comment by tkittel** [comment]
Thanks for the explanation and the links, let us hope the conda developers get this fixed at some point :smile: : 

And thanks for the invitation to the monthly gatherings, I will keep a lookout for a time without conflicting meetings etc. :+1:
