### ISSUE TITLE
Error when running OpenMC in development version

### ISSUE THREAD

**Issue by ahnaf-tahmid-chowdhury** [openmc-dev/openmc#2664]
## Bug Description
When using the dev version of OpenMC, I encountered an error when trying to run the `openmc.run()` or `openmc.plot_geometry()` functions. The error message is as follows:

```python
Traceback (most recent call last):
  File "/home/tahmid/Documents/Minimal_no_merge/main.py", line 48, in <module>
    openmc.plot_geometry()
  File "/opt/nuclear-boy/lib/python3.10/site-packages/openmc/executor.py", line 154, in plot_geometry
    _run(args, output, cwd)
  File "/opt/nuclear-boy/lib/python3.10/site-packages/openmc/executor.py", line 97, in _run
    p = subprocess.Popen(args, cwd=cwd, stdout=subprocess.PIPE,
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'openmc'
```

This issue does not occur with the stable version of OpenMC.

## Steps to Reproduce
1. Install the development version of OpenMC.
2. Create a script using the `openmc.run()` or `openmc.plot_geometry()` functions.
3. Run the script.
4. Observe the error message.

## Environment
- Os: Ubuntu 22.04
- Version: dev
- Installation Method: from source

## Additional Information
I suspect that the error might be related to a missing or improperly set executable path when using the dev version. The same code works without errors in the stable version.

Please let me know if there's any additional information I can provide to help diagnose and resolve this issue.

**Comment by ahnaf-tahmid-chowdhury** [comment]
I've identified the problem, it appears that `OpenMC` utilizes `Catch2` as a vendor, and during the module installation, I realized that I had previously installed `Catch2` using `sudo` privileges. This was the root cause of the issue I encountered. I want to express my gratitude for your assistance throughout this process.
