### ISSUE TITLE
Depletion flux mode reaction rate reconstruction broken

### ISSUE THREAD

**Issue by gridley** [openmc-dev/openmc#2692]
## Bug Description

The flux mode reaction rate reconstruction method causes OpenMC to crash after step 0, because other nuclides from the chain are not being loaded.

## Steps to Reproduce

Go to `examples/pincell_depletion`, and define the depletion operator as:
```
chain_file = 'chain_simple.xml'
op = openmc.deplete.CoupledOperator(model, chain_file,
        reaction_rate_mode="flux", reaction_rate_opts=
        {'energies':openmc.mgxs.GROUP_STRUCTURES['SHEM-361']})
```

The simulation crashes with the message:

```
 k-effective (Collision)     = 1.16273 +/- 0.00361
 k-effective (Track-length)  = 1.15901 +/- 0.00440
 k-effective (Absorption)    = 1.16493 +/- 0.00321
 Combined k-effective        = 1.16348 +/- 0.00277
 Leakage Fraction            = 0.00000 +/- 0.00000

Traceback (most recent call last):
  File "/home/gavin/Code/openmc/openmc/lib/nuclide.py", line 115, in __getitem__
    _dll.openmc_get_nuclide_index(key.encode(), index)
  File "/home/gavin/Code/openmc/openmc/lib/error.py", line 33, in _error_handler
    raise exc.DataError(msg)
openmc.exceptions.DataError: No nuclide named 'I135' has been loaded.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/gavin/Code/openmc/examples/pincell_depletion/run_depletion.py", line 100, in <module>
    integrator.integrate()
  File "/home/gavin/Code/openmc/openmc/deplete/abc.py", line 790, in integrate
    n, res = self._get_bos_data_from_operator(i, source_rate, n)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gavin/Code/openmc/openmc/deplete/abc.py", line 743, in _get_bos_data_from_operator
    res = self.operator(x, source_rate)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gavin/Code/openmc/openmc/deplete/coupled_operator.py", line 457, in __call__
    rates = self._calculate_reaction_rates(source_rate)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gavin/Code/openmc/openmc/deplete/openmc_operator.py", line 502, in _calculate_reaction_rates
    tally_rates = self._rate_helper.get_material_rates(
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/gavin/Code/openmc/openmc/deplete/helpers.py", line 391, in get_material_rates
    nuc = openmc.lib.nuclides[name]
          ~~~~~~~~~~~~~~~~~~~^^^^^^
  File "/home/gavin/Code/openmc/openmc/lib/nuclide.py", line 118, in __getitem__
    raise KeyError(str(e))
KeyError: "No nuclide named 'I135' has been loaded."

```

## Environment

"I use arch btw"

```
gpad% openmc -v
OpenMC version 0.13.4
Git SHA1: bf7a079b2c84d02f3636dd1bd185e1e326469189
Copyright (c) 2011-2023 MIT, UChicago Argonne LLC, and contributors
MIT/X license at <https://docs.openmc.org/en/latest/license.html>
Build type:            RelWithDebInfo
Compiler ID:           GNU 13.2.1
MPI enabled:           no
Parallel HDF5 enabled: no
PNG support:           yes
DAGMC support:         no
libMesh support:       no
MCPL support:          no
NCrystal support:      no
Coverage testing:      no
Profiling flags:       no

```

**Comment by paulromano** [comment]
Thanks for reporting @gridley. I just submitted a fix -- would appreciate your review on it!
